services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/budget_tracker
      - SECRET_KEY=apppassword
      - JWT_SECRET_KEY=jwtpassword
    depends_on:
      - db
    command: >
      bash -c "python init_db.py && 
              gunicorn --bind 0.0.0.0:8000 --reload backend.app:app"

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=budget_tracker
    ports:
      - "5432:5432"

volumes:
  postgres_data: